### ISSUE TITLE
starboard 

### ISSUE THREAD

**Issue by L3NNY0969** [erickang21/dat-banana-bot#15]
The starboard keeps posting new messages when multiply people star one message. Fix it to look almost like r.danny's, where it just edits star count.

**Comment by batshalregmi** [comment]
yeah

**Comment by ravener** [comment]
He's too gay to fix it

**Comment by batshalregmi** [comment]
too lazy

**Comment by L3NNY0969** [comment]
this becoming a popular issue lol

**Comment by batshalregmi** [comment]
yeah

**Comment by batshalregmi** [comment]
cause someone is lazy and playing LoL

**Comment by L3NNY0969** [comment]
*cough, cough* 

banana boi

**Comment by L3NNY0969** [comment]
I see u playing LoL xddd

**Comment by batshalregmi** [comment]
I see u playing with that tapeball xddd

**Comment by mysteiige** [comment]
Yes, banana boi, that was a nessecary comment kthnxbai

**Comment by batshalregmi** [comment]
i see u smhhhhhhing  me

**Comment by batshalregmi** [comment]
i see u ack staping me

**Comment by batshalregmi** [comment]
i see u honestly...ing me

**Comment by batshalregmi** [comment]
i seee u banana bot is gaying

**Comment by batshalregmi** [comment]
i see u omfing

**Comment by batshalregmi** [comment]
i see u real fix for poll now kthxbye

**Comment by batshalregmi** [comment]
ok i'll stop for now

**Comment by L3NNY0969** [comment]
what issue have i created

**Comment by batshalregmi** [comment]
i see u https://herokuis.a-bad.hosting me

**Comment by batshalregmi** [comment]
u better not close this

**Comment by ravener** [comment]
K unlocked and reopened lmao

**Comment by batshalregmi** [comment]
YEYSYSYSY

**Comment by batshalregmi** [comment]
i see ur playing vs code

**Comment by batshalregmi** [comment]
atom = everything

**Comment by batshalregmi** [comment]
https://atom.io/beta

**Comment by ravener** [comment]
Lol

**Comment by StellaraUmbrix** [comment]
havent been played with. yayeet
