### ISSUE TITLE
Serverunmute doesn't work

### ISSUE THREAD

**Issue by mysteiige** [erickang21/dat-banana-bot#16]
You were there in the server when it happened

**Comment by ravener** [comment]
Do i kno u on discord?

**Comment by mysteiige** [comment]
Probably

**Comment by ravener** [comment]
And make sure bot have perms and stuff, also there's a bug that it might make user talk in almost all channels even ones it shouldn't

**Comment by mysteiige** [comment]
Bot has all perms, and it was working yesterday sooo

**Comment by ravener** [comment]
What happens when u use it?

**Comment by mysteiige** [comment]
It gets stuck on unmuting user and doesn't remove the role

**Comment by ravener** [comment]
Role? Its supposed to edit the permissions for the user on the channels.

**Comment by mysteiige** [comment]
It doesn't. It adds a role

**Comment by erickang21** [comment]
I wanted it to add a role and not set user specific permissions because 
1) that would take too long
2) it would allow users to send messages in channels they weren't allowed to before.
I'm gonna temporarily leave this broken until I have a better idea for it.

**Comment by mysteiige** [comment]
@bananaboy21 You just have to tell the owner after doing it to make sure the bots role is above the muted role.

**Comment by L3NNY0969** [comment]
wow 2 months. Gonna keep it open for "memories"

**Comment by mysteiige** [comment]
so uh, did it get fixed?

**Comment by ravener** [comment]
Old issue, closing
