### ISSUE TITLE
Music queue is broke af

### ISSUE THREAD

**Issue by mysteiige** [erickang21/dat-banana-bot#18]
Bruh, fix it asap. It's annoying as fucc

**Comment by erickang21** [comment]
I've tried many times, and asked others to help, but just doesn't seem to fix itself so I gave up. might try again soon

**Comment by mysteiige** [comment]
Bro, maybe take it to the d.py server?

**Comment by erickang21** [comment]
@BloodyPikachu I've never been happier to say this, and I never thought I had to, but music queue is fixed. Cheers!
