### ISSUE TITLE
Modlogs dont show pics

### ISSUE THREAD

**Issue by L3NNY0969** [erickang21/dat-banana-bot#19]
When i post a picture to test it, the I deleted it, and it didnt show in modlogs

**Comment by erickang21** [comment]
currently broke for no apparent reason. code looks all correct. will be working on soon

**Comment by L3NNY0969** [comment]
kk

**Comment by L3NNY0969** [comment]
kk

i need just in case someone posts p0rn and delete / sanjay leaks

**Comment by ravener** [comment]
Images are gone from discord cdn after delete, nothing we can do.
